# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""Generate SpeechRecognitionModels.h from models.yaml."""

import yaml


def gen_models_header(output, input):
    with open(input) as f:
        data = yaml.safe_load(f)

    models = data["models"]

    output.write(
        "/* This file is generated by gen_speech_models.py. Do not edit. */\n"
        "#pragma once\n\n"
        "#include <stdint.h>\n\n"
        "namespace mozilla::dom {\n\n"
        "struct SpeechRecognitionModelInfo {\n"
        "  const char* id;\n"
        "  const char* const* locales; // null-terminated; empty (first==nullptr) = fallback\n"
        "  const char* repo;\n"
        "  const char* filename;\n"
        "  const char* revision;\n"
        "  uint32_t size_mb;\n"
        "  const char* quant;\n"
        "  uint32_t latency_ms;\n"
        "  bool is_default;\n"
        "  bool is_streaming; // true = streaming RNN-T, false = offline CTC batch\n"
        "};\n\n"
    )

    # Emit per-model locale arrays.
    for m in models:
        locales = m["locales"]
        entries = (
            ", ".join(f'"{l}"' for l in locales) + (", " if locales else "") + "nullptr"
        )
        output.write(
            f"static const char* const kSpeechModelLocales_{m['id']}[] = {{{entries}}};\n"
        )

    output.write("\n")

    # Emit the table, sentinel-terminated.
    output.write(
        "static const SpeechRecognitionModelInfo kSpeechRecognitionModels[] = {\n"
    )
    for m in models:
        is_default = "true" if m.get("default", False) else "false"
        is_streaming = "true" if m.get("streaming", True) else "false"
        output.write(
            f'  {{"{m["id"]}", kSpeechModelLocales_{m["id"]},\n'
            f'   "{m["repo"]}", "{m["filename"]}", "{m["revision"]}",\n'
            f'   {m["size_mb"]}, "{m["quant"]}", {m["latency_ms"]}, {is_default}, {is_streaming}}},\n'
        )
    output.write(
        "  {nullptr, nullptr, nullptr, nullptr, nullptr, 0, nullptr, 0, false}\n"
    )
    output.write("};\n\n")

    output.write("}  // namespace mozilla::dom\n")
